(function(){var SoundManager=Laya.SoundManager;var bombSmokeUpdate=function(){this.scale-=0.03;if(this.scale<0)
{this.scale=0;this.life=0;}};var bombUpdate=function(){var smoke=particleSystem.createParticle(SPP.SpriteImage);var r=1.42*g_AssetsMgr.bomb.width*0.5;var px=this.position.x+r*Math.cos(this.rotation-SPP.MathUtils.toRadian(90));var py=this.position.y+r*Math.sin(this.rotation-SPP.MathUtils.toRadian(90));smoke.init(px,py,Infinity,g_AssetsMgr.star,topContext);smoke.onUpdate=bombSmokeUpdate;smoke.scale=0.8;smoke.damp.reset(0,0);smoke.velocity.reset(0,-(1+Math.random()*1));smoke.velocity.rotate(360*Math.random());smoke.addForce("g",gravity);};var explodeSmokeUpdate=function(){this.scale-=0.02;if(this.scale<0)
{this.scale=0;this.life=0;}};var bombExplode=function(target){for(var i=0;i<150;i++)
{var smoke=particleSystem.createParticle(SPP.SpriteImage);smoke.init(target.position.x,target.position.y,Infinity,g_AssetsMgr.star,topContext);smoke.onUpdate=explodeSmokeUpdate;smoke.scale=2;smoke.damp.reset(0,0);smoke.velocity.reset(0,-(3+Math.random()*7));smoke.velocity.rotate(360*Math.random());smoke.addForce("g",gravity);}};throwBomb=function(){var p=bombSystem.createParticle(FruitGame.Fruit);p.init(gameWidth*0.5+(1-Math.random()*2)*300,gameHeight
+g_AssetsMgr.bomb.height,Infinity,g_AssetsMgr.bomb,g_AssetsMgr.shadow,middleContext);p.velocity.reset(0,-(18+Math.random()*3));p.velocity.rotate(8-Math.random()*16);p.damp.reset(0,0);p.addForce("g",gravity);p.onUpdate=bombUpdate;p.addEventListener("dead",missBomb);p.bottomY=gameHeight+g_AssetsMgr.bomb.height;SoundManager.playMusic("sound/throw-bomb.mp3");SoundManager.playSound("sound/throwbomb.mp3",1);};cutBomb=function(target){SoundManager.stopMusic("sound/throw-bomb.mp3");var createBubbles=function()
{var bubbles=particleSystem.createParticle(SPP.SpriteImage);bubbles.init(target.position.x,target.position.y,1/0,Laya.loader.getRes("ui/qipao.png"),topContext);bubbles.scale=0.7;bubbles.velocity.reset(0,-(4+Math.random()*4));bubbles.velocity.rotate(360*Math.random());bubbles.addForce("g",gravity);}
if(g_PlayerData.useBuffList[0]>0)
{createBubbles();g_PlayerData.useBuffList[0]--;target.life=0;}
else if(BuffList&&BuffList["ignorebomb"])
{createBubbles();BuffList["ignorebomb"]--;target.life=0;}else{if(g_GameData.model==GameModel.ARCADE){g_PlayerData.curScore-=10;if(g_PlayerData.curScore<0)g_PlayerData.curScore=0;g_EventMgr.Event(Notifition.UpdateScore);SoundManager.playSound("sound/bomb-explode.mp3",1);bombExplode(target);target.life=0;}else{var r=target.rotation;target.removeAllForces();target.init(target.position.x,target.position.y,Infinity,g_AssetsMgr.bomb,g_AssetsMgr.shadow,middleContext);target.rotation=r;target.rotationStep=0;playBombEff(target);}}};missBomb=function(e){SoundManager.stopMusic("sound/throw-bomb.mp3");}
var pos=new Laya.Vector3(0,0,0);playBombEff=function(target){if(img_bomb&&img_bomb.parent)return;SoundManager.playSound("sound/bomb-explode.mp3",1);if(img_bomb==null){img_bomb=new Laya.Image();img_bomb.skin="ui/baise.png";img_bomb.width=1280;img_bomb.height=720;}
img_bomb.alpha=0;bottomCanvas.addChild(img_bomb);eff_bomb=uiScene.addChild(Laya.Sprite3D.load("eff/eff_zhadan.lh"));var x=target.position.x/Laya.stage.width*Laya.Render.canvas.width;var y=target.position.y/Laya.stage.height*Laya.Render.canvas.height;camera.convertScreenCoordToOrthographicCoord(new Laya.Vector3(x,y,0),pos);eff_bomb.transform.position=pos;Laya.Tween.to(img_bomb,{alpha:1},1500,Laya.Ease.backInOut,Laya.Handler.create(this,function(){target.life=0;if(img_bomb&&img_bomb.parent)
img_bomb.parent.removeChild(img_bomb);if(eff_bomb&&eff_bomb.parent)
eff_bomb.parent.removeChild(eff_bomb);g_GameMgr.gameOver();}));}}());